---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - multideployment.xplatform.api
  resources:
  - groupdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multideployment.xplatform.api
  resources:
  - groupdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - multideployment.xplatform.api
  resources:
  - groupdeployments/status
  verbs:
  - get
  - patch
  - update
