apiVersion: multideployment.xplatform.api/v1
kind: GroupDeployment
metadata:
  labels:
    app.kubernetes.io/name: group-deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: groupdeployment-sample
spec:
  # TODO(user): Add fields here
