apiVersion: multideployment.xplatform.api/v1
kind: GroupDeployment
metadata:
  labels:
    app.kubernetes.io/name: group-deployment-operator
    app.kubernetes.io/managed-by: kustomize
  name: groupdeployment-sample
  namespace: groupdeployment-operator-system
spec:
  owner: platform-dev@xplatform.api
  blueDeployment: nginx:1.27
  greenDeployment: nginx:1.26.1
